// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information
function enemy_start_data(enm_num){
	switch(enm_num){
		case 0:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 1:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 2:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 3:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 4:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 5:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 6:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 7:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 8:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 9:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 10:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 11:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 12:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 13:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 14:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 15:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 16:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 17:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 18:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 19:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 20:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 21:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 22:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 23:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 24:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 25:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 26:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 27:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 28:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 29:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 30:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 31:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 32:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 33:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 34:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 35:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 36:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 37:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 38:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 39:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 40:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 41:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 42:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 43:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 44:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 45:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 46:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 47:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 48:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 49:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 50:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 51:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 52:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 53:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 54:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 55:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 56:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 57:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 58:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 59:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		case 60:{
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
			break;
		default:{
			sd("enemy_start_data Default");
			opt = ds_map_create();
			ds_map_add(opt,"name","jopa");
			ds_map_add(opt,"hp",100);
			ds_map_add(opt,"speed",1);
			ds_map_add(opt,"weapon",0);
			ds_map_add(opt,"skill","");
			ds_map_add(opt,"skill_timeout",10);
			ds_map_add(opt,"damage",5);
			ds_map_add(opt,"dm_timeout",2);
			ds_map_add(opt,"price",10);
			ds_map_add(opt,"weapon_type",0);
			//opt2//
			//opt3//
			//opt4//
			//opt5//
			//opt6//
			//opt7//
			//opt8//
			//opt9//
			//opt10/
			//opt11/
			//opt12/
			//opt13/
			//opt14/
			//opt15/
			//opt16/
			//opt17/
			//opt18/
			//opt19/
			//opt20/
			//opt21/
			//opt22/
			//opt23/
			//opt24/
			//opt25/
			//opt26/
			//opt27/
			//opt28/
			//opt29/
			//opt30/
		}
	}
	
}